### ISSUE TITLE
BROKERS: Select All Languages

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Sofee.Core#22]

**Comment by ElbekDeveloper** [comment]
@hassanhabib I was doing this task. Could you please assign this to me?

**Comment by ElbekDeveloper** [comment]
Neither I could refer you @hassanhabib  as reviewer, nor I could link this issue to the PR. Looking forward for your precious feedback...

**Comment by ElbekDeveloper** [comment]
I think we can close this issue @hassanhabib
