### ISSUE TITLE
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Metadata.ITagsMetadata' from assembly 'Microsoft.AspNetCore.Http.Abstractions

### ISSUE THREAD

**Issue by kushalbDeveloper** [hassanhabib/Sofee.Core#9]
![image](https://user-images.githubusercontent.com/93524224/140395803-49334007-57ff-4a13-a948-5ec5ed665530.png)

**Comment by kushalbDeveloper** [comment]
@hassanhabib  Followed tutorial but i got this TypeLoadException Issue. After i downgrade Swashbuckle.AspNetCore from 6.2.3 to 5.0 everything works.Thanks

**Comment by kushalbDeveloper** [comment]
![image](https://user-images.githubusercontent.com/93524224/140396536-41fa3fc6-d2e0-421b-8c5a-df075bb76222.png)

**Comment by hassanhabib** [comment]
@kushalbDeveloper try upgrading the version of `RESTFulSense`
